---
title: "Real-time theming with bslib and thematic"
runtime: shiny
output: 
  html_document:
    code_folding: show
    theme:
      color-contrast-warnings: false
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

## R Markdown



## Themed Plots {.tabset .tabset-pills}

When running this document with [`{thematic}`](https://rstudio.github.io/thematic/) installed, the `thematic::thematic_rmd(font = "auto")` effectively translates `theme` (CSS) settings to new global theming defaults for `{ggplot2}`, `{lattice}`, and `{base}` R graphics:

### ggplot2

```{r, message = FALSE}
library(ggplot2)

renderPlot({
  ggplot(mpg, aes(displ, hwy)) +
    geom_point() + geom_smooth()
})
```

### lattice

```{r}
renderPlot({
  lattice::show.settings()
})
```

### base

```{r}
renderPlot({
  plot(pressure, col = thematic::thematic_get_option("accent"))
})
```
